services:
  - name: cf-hasura
    type: web
    env: docker
    dockerfilePath: ./hasura/Dockerfile
    dockerContext: ./hasura
    # See https://hasura.io/docs/1.0/graphql/core/api-reference/health.html
    healthCheckPath: /healthz
    envVars:
      - key: HASURA_GRAPHQL_DATABASE_URL
        fromDatabase:
          name: elefante
          property: connectionString
      - key: HASURA_GRAPHQL_ADMIN_SECRET
        generateValue: true

      # If we don't set this then render will incorrectly infer it as 9691 since
      # the hasura/graphql-engine:vX.X.X.cli-migrations-v3 image first starts a
      # temporary server to run the appropriate migrations and metadata updates.
      - key: PORT
        value: 8080

      - key: API_SECRET
        fromService:
          name: cf-next
          type: web
          envVarKey: API_SECRET

      - key: NEXT_HOST
        fromService:
          name: cf-next
          type: web
          property: host
      - key: NEXT_PORT
        fromService:
          name: cf-next
          type: web
          property: port

  - name: cf-next
    type: web
    env: node
    buildCommand: cd next/ && yarn install --frozen-lockfile && yarn run build
    startCommand: cd next/ && yarn run start
    healthCheckPath: /api/healthz
    envVars:
      # See https://community.render.com/t/render-doesnt-respect-engines-setting-in-package-json-as-the-docs-suggest/2805/2
      - key: NODE_VERSION
        value: 16.13.0

      # Hasura stuff
      - key: HASURA_HOST
        fromService:
          name: cf-hasura
          type: web
          property: host
      - key: HASURA_PORT
        value: 10000
      - key: HASURA_GRAPHQL_ADMIN_SECRET
        fromService:
          name: cf-hasura
          type: web
          envVarKey: HASURA_GRAPHQL_ADMIN_SECRET

      - key: API_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: GITHUB_API_TOKEN
        sync: false

databases:
  # This is the Render name of the database, not the postgres name of the
  # database. Render may add a suffix. In our case that doesn't seem to be the
  # case: both are "elefante".
  - name: elefante
