# Hasura CLI metadata

version: 2

# Coincidentally, the default value is http://localhost:8080.
# endpoint: http://localhost:8080
# endpoint: https://cuddlefish-hasura.herokuapp.com/

# This matches the definition in `docker-compose.yaml` for development purposes.
admin_secret: hasurasecret

# This is necessary otherwise hasura CLI looks for a single metadata file.
metadata_directory: metadata
