version: 2
endpoint: https://cuddlefish-hasura.herokuapp.com/
# This is necessary otherwise hasura CLI looks for a single metadata file.
metadata_directory: metadata
# This seems to be completely useless:
# actions:
#   kind: synchronous
#   handler_webhook_baseurl: http://localhost:3000
