# Development config for postgres/hasura.

# TODO: set up metadata stuff...

# See https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix for the latest version info.
version: "3.8"
services:
  postgres:
    # As of Nov 2020, Render runs postgres 11: https://render.com/docs/databases#database-versions--upgrades. Although
    # there is a feature request to add support for other versions: https://feedback.render.com/features/p/postgres-12.
    image: postgres:11
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      # Use the `hasura console` command instead.
      # HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: hasurasecret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      # This is the same in dev and prod.
      HASURA_GRAPHQL_JWT_SECRET: "{\"type\": \"RS512\", \"key\": \"-----BEGIN CERTIFICATE-----\nMIIDAzCCAeugAwIBAgIJK5EEMf+vKw87MA0GCSqGSIb3DQEBCwUAMB8xHTAbBgNV\nBAMTFGN1ZGRsZWZpc2guYXV0aDAuY29tMB4XDTIwMDIxODAwNTkyMloXDTMzMTAy\nNzAwNTkyMlowHzEdMBsGA1UEAxMUY3VkZGxlZmlzaC5hdXRoMC5jb20wggEiMA0G\nCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK7iX8m7MZoxb1WTaNstbp75Cm5tLK\nwDKnMJxFmJjlLXJiy/Q/oBosheedt6UKdciVmIU7cuMz/DWd5lYwYKVrnQ6Tbp43\nYIlTLUmTAK4Zys8VjmoA7aJwcrhtnLgjx8YTSFAORWw+Rsosdd0MIWiVClFdVG/x\n0kE1Dkc/ZzcZWWc7HiR1U9skBBOcRoCgD5uXZLA3As53npcXoMTkHa1/mzggXM1w\nY0aJHuqRNZ8l394104oxRWbinwQFCpLMF7VTKOfYfkY1twDGp0NnITjf39N76xct\nmercjCVI4Z9JFhTkjAtTZSteb4fA80JN87a9/enOSrRwFlM3E4lv6xfpAgMBAAGj\nQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFI6vxTDEjBhGCD+Wk1Pp8F/i\nBHseMA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOCAQEAjfctua1ijHP7\nFK/EheeDotyar/tdhrUxp1yaszQyF9O+lK05rCRe0jLhYFdg38duTGrZZ9BDtLJA\n0eMVrOgntn1blMtrQN8noZIOmOsNsbnTB8DUG99jwP23fPxt9XLr5/c+xwMXzJom\nT/153BriI9090VsCJqzKgO2wHreSPPAWPfX44goZpzU9GOFJu4ByQhRonqIy8yNX\nBZPAzIQ07QoMrYQ2yC/oB8ciF5VRudQgJj7KFfezT7fL8S8Tzpf6myi7Bq5249Q6\n4l9u/uBcCIfBsnPHtj7P+JuUsSy8+Ajfo6vMmcHXgxds3RqJ5Y9f9TubYEwgwIUV\n0RcLNNvodw==\n-----END CERTIFICATE-----\"}"

# See https://docs.docker.com/compose/compose-file/#volumes.
volumes:
  db_data:
