# Development config for postgres/hasura on Linux.

# See https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix for the latest version info.
version: "3.9"
services:
  postgres:
    image: postgres:14
    network_mode: host
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    build: .
    depends_on:
      - "postgres"
    network_mode: host
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgrespassword@localhost:5432/postgres"

      # Default logging minus websocket-log:
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log"
      # HASURA_GRAPHQL_LOG_LEVEL: "debug"

      # Don't enable DEV_MODE in prod!
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "hasurasecret"

      API_SECRET: "apisecret"

      API_HOST: "localhost"
      API_PORT: 3001
      NEXT_HOST: "localhost"
      NEXT_PORT: 3002

  # pgadmin:
  #   image: dpage/pgadmin4
  #   network_mode: host
  #   environment:
  #     PGADMIN_LISTEN_PORT: 5050
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     GUNICORN_ACCESS_LOGFILE: /dev/null

# See https://docs.docker.com/compose/compose-file/#volumes.
volumes:
  db_data:
