# Development config for postgres/hasura.

# TODO: set up metadata stuff...

# See https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix for the latest version info.
version: "3.8"
services:
  postgres:
    # As of Nov 2020, Render runs postgres 11: https://render.com/docs/databases#database-versions--upgrades. Although
    # there is a feature request to add support for other versions: https://feedback.render.com/features/p/postgres-12.
    image: postgres:11
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      # Use the `hasura console` command instead.
      # HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: hasurasecret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous

# See https://docs.docker.com/compose/compose-file/#volumes.
volumes:
  db_data:
