[package]
name = "api"
version = "0.0.0"
authors = ["Samuel Ainsworth <skainsworth@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
chrono = "0.4"
cookie = "0.14"
failure = "0.1"
futures = "0.3"
git2 = "0.13"
graphql_client = "0.9"
hyper = "0.13"
lazy_static = "1.4"
log = "0.4"
paseto = "1.0"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros"] }
url = "2.1"

# Published juniper packages don't work. See https://github.com/graphql-rust/juniper/issues/741.
# See https://github.com/rust-lang/cargo/issues/1462#issuecomment-87002475.
# We should be able to upgrade to juniper 0.8.1 and get this fixed up.
juniper = { git = "https://github.com/graphql-rust/juniper", rev = "45c16ac" }
juniper_hyper = { git = "https://github.com/graphql-rust/juniper", rev = "45c16ac" }

# For development:
# juniper = { path = "../../juniper/juniper" }
# juniper_hyper = { path = "../../juniper/juniper_hyper" }
