[package]
name = "api"
version = "0.0.0"
authors = ["Samuel Ainsworth <skainsworth@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
failure = "0.1.6"
futures = "0.3.4"
git2 = "0.11.0"
graphql_client = "0.8.0"
hyper = "0.13.2"
# juniper = { version = "0.14.2", features = ["async"] }
juniper = { path = "../../juniper/juniper" }
juniper_hyper = { path = "../../juniper/juniper_hyper", features = ["async"] }
log = "0.4.8"
reqwest = { version = "0.10.1", features = ["json"] }
serde = { version = "1.0.104", features = ["derive"] }
# serde_json = "1.0.48"
tokio = { version = "0.2.11", features = ["macros"] }
